from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, JSON, Float, Text, Enum, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from ..platform.database import Base
import enum


class AssessmentStatus(str, enum.Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    COMPLETED_DUE_TO_TIMEOUT = "completed_due_to_timeout"
    EXPIRED = "expired"


class Assessment(Base):
    __tablename__ = "assessments"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, ForeignKey("organizations.id"), index=True)
    candidate_id = Column(Integer, ForeignKey("candidates.id"), index=True)
    task_id = Column(Integer, ForeignKey("tasks.id"), index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), index=True, nullable=True)
    application_id = Column(Integer, ForeignKey("candidate_applications.id"), index=True, nullable=True)
    token = Column(String, unique=True, index=True)
    status = Column(Enum(AssessmentStatus), default=AssessmentStatus.PENDING)
    duration_minutes = Column(Integer, default=30)
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    expires_at = Column(DateTime(timezone=True))
    score = Column(Float)
    tests_passed = Column(Integer)
    tests_total = Column(Integer)
    code_quality_score = Column(Float)
    time_efficiency_score = Column(Float)
    ai_usage_score = Column(Float)
    test_results = Column(JSON)
    ai_prompts = Column(JSON)
    code_snapshots = Column(JSON)
    timeline = Column(JSON)
    e2b_session_id = Column(String)
    assessment_repo_url = Column(String, nullable=True)
    assessment_branch = Column(String, nullable=True)
    clone_command = Column(Text, nullable=True)
    final_repo_state = Column(String, nullable=True)
    git_evidence = Column(JSON, nullable=True)
    completed_due_to_timeout = Column(Boolean, default=False)
    ai_mode = Column(String, default="claude_cli_terminal", nullable=False)
    cli_session_pid = Column(Integer, nullable=True)
    cli_session_state = Column(String, nullable=True)
    cli_session_started_at = Column(DateTime(timezone=True), nullable=True)
    cli_session_last_seen_at = Column(DateTime(timezone=True), nullable=True)
    cli_transcript = Column(JSON, nullable=True)
    is_timer_paused = Column(Boolean, default=False, nullable=False)
    paused_at = Column(DateTime(timezone=True), nullable=True)
    pause_reason = Column(String, nullable=True)
    total_paused_seconds = Column(Integer, default=0, nullable=False)
    workable_candidate_id = Column(String)
    workable_job_id = Column(String)
    posted_to_workable = Column(Boolean, default=False)
    posted_to_workable_at = Column(DateTime(timezone=True))
    invite_channel = Column(String, default="manual", nullable=False)
    invite_sent_at = Column(DateTime(timezone=True), nullable=True)
    credit_consumed_at = Column(DateTime(timezone=True), nullable=True)
    # Prompt scoring fields (Phase 2)
    prompt_quality_score = Column(Float, nullable=True)
    prompt_efficiency_score = Column(Float, nullable=True)
    independence_score = Column(Float, nullable=True)
    context_utilization_score = Column(Float, nullable=True)
    design_thinking_score = Column(Float, nullable=True)
    debugging_strategy_score = Column(Float, nullable=True)
    written_communication_score = Column(Float, nullable=True)
    learning_velocity_score = Column(Float, nullable=True)
    error_recovery_score = Column(Float, nullable=True)
    requirement_comprehension_score = Column(Float, nullable=True)
    calibration_score = Column(Float, nullable=True)
    prompt_fraud_flags = Column(JSON, nullable=True)
    prompt_analytics = Column(JSON, nullable=True)
    browser_focus_ratio = Column(Float, nullable=True)
    tab_switch_count = Column(Integer, default=0)
    time_to_first_prompt_seconds = Column(Integer, nullable=True)
    cv_file_url = Column(String, nullable=True)
    cv_filename = Column(String, nullable=True)
    cv_uploaded_at = Column(DateTime(timezone=True), nullable=True)
    final_score = Column(Float, nullable=True)
    score_breakdown = Column(JSON, nullable=True)
    score_weights_used = Column(JSON, nullable=True)
    flags = Column(JSON, nullable=True)
    scored_at = Column(DateTime(timezone=True), nullable=True)
    total_duration_seconds = Column(Integer, nullable=True)
    total_prompts = Column(Integer, nullable=True)
    total_input_tokens = Column(Integer, nullable=True)
    total_output_tokens = Column(Integer, nullable=True)
    tests_run_count = Column(Integer, nullable=True)
    tests_pass_count = Column(Integer, nullable=True)
    # CV-Job fit matching (Phase 2)
    cv_job_match_score = Column(Float, nullable=True)
    cv_job_match_details = Column(JSON, nullable=True)
    manual_evaluation = Column(JSON, nullable=True)  # { category_scores: { key: { score, evidence } }, overall_score?, strengths?, improvements? }
    candidate_feedback_json = Column(JSON, nullable=True)
    candidate_feedback_generated_at = Column(DateTime(timezone=True), nullable=True)
    candidate_feedback_sent_at = Column(DateTime(timezone=True), nullable=True)
    candidate_feedback_ready = Column(Boolean, default=False, nullable=False)
    candidate_feedback_enabled = Column(Boolean, default=True, nullable=False)
    interview_debrief_json = Column(JSON, nullable=True)
    interview_debrief_generated_at = Column(DateTime(timezone=True), nullable=True)
    is_demo = Column(Boolean, default=False, nullable=False)
    demo_track = Column(String, nullable=True)
    demo_profile = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    organization = relationship("Organization", back_populates="assessments")
    candidate = relationship("Candidate", back_populates="assessments")
    task = relationship("Task")
    role = relationship("Role", back_populates="assessments")
    application = relationship("CandidateApplication", back_populates="assessments")
    sessions = relationship("AssessmentSession", back_populates="assessment")
