"""Event-handler primitives for the platform's auto-trigger flows.

Single place that says "given this event, here are the auto-tasks to
enqueue." Today there are two events:

- ``on_role_jd_attached(role)`` — fires when a JD is attached or
  re-uploaded to a role. Enqueues interview-focus generation.
- ``on_application_created(app, *, score)`` — fires when an application
  is ingested from any source (manual upload, Workable sync). Enqueues
  the per-candidate auto work (interview pack, auto-reject) and, when
  ``score=True``, the scoring job for ingestion paths that promise immediate
  evaluation (public requisition apply and recruiter CV upload).

Policy reminder: Workable bulk sync calls these handlers with ``score=False``
so one import does not enqueue an unbounded burst. For an enabled role, the
bounded cohort worker drains that backlog automatically; no recruiter scoring
click is required. Recruiter uploads and native requisition applications pass
``score=True`` for the low-latency path; the latter is safe because Turn on is
credit/budget/readiness gated.

These helpers must be cheap and synchronous — they only schedule Celery
tasks via ``.delay()``. The actual Claude work happens on the worker.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models.candidate_application import CandidateApplication
    from ..models.role import Role

logger = logging.getLogger("taali.events")


def on_role_jd_attached(role: "Role") -> None:
    """Schedule auto-tasks for a role that just had a JD attached.

    No-ops when there's no JD text yet; the page can still return without
    waiting for the worker.
    """
    if role is None or not (getattr(role, "job_spec_text", "") or "").strip():
        return
    role_id = int(getattr(role, "id", 0) or 0)
    if role_id <= 0:
        return
    try:
        from ..tasks.automation_tasks import generate_role_interview_focus

        generate_role_interview_focus.delay(role_id)
        logger.info("on_role_jd_attached enqueued role_id=%s", role_id)
    except Exception:  # pragma: no cover — defensive: never let scheduling break the request
        logger.exception("on_role_jd_attached scheduling failed role_id=%s", role_id)


def on_application_created(
    app: "CandidateApplication",
    *,
    score: bool = False,
    score_force: bool = False,
) -> None:
    """Schedule auto-tasks for a freshly-ingested application.

    Always schedules:
    - auto-reject pre-screen evaluation (cheap — no Claude call; uses
      pre-existing Workable scores)

    When ``score=True``, also enqueues a CV match scoring job. Pass this
    from ingestion flows that promise immediate evaluation: native public
    applications, manual CV upload endpoints, and explicit Score/Rescore.

    Interview-pack regeneration is **not** scheduled here. Generating a
    pack costs ~$0.013 in Haiku 4.5 spend per candidate; doing it for
    every imported candidate (most of whom are never scored) was the
    dominant cost driver on 2026-05 and explicitly out of policy. The
    pack is now generated by ``cv_score_orchestrator`` after a candidate
    passes pre-screen and gets a v3 score — the only point at which the
    pack carries useful, candidate-specific signal.

    The Workable bulk sync passes ``score=False`` so importing N candidates
    doesn't burst-enqueue N scoring jobs. An enabled role's bounded cohort
    sweep drains them automatically; the explicit scoring controls remain
    operator recovery/override surfaces.
    """
    if app is None:
        return
    application_id = int(getattr(app, "id", 0) or 0)
    if application_id <= 0:
        return
    try:
        from ..tasks.automation_tasks import run_application_auto_reject

        run_application_auto_reject.delay(application_id)
    except Exception:  # pragma: no cover — defensive
        logger.exception(
            "on_application_created auto-task scheduling failed application_id=%s",
            application_id,
        )

    # CV section parsing (Haiku 4.5) runs async so neither the Workable sync
    # loop nor the upload request blocks on a Claude call. Enqueue only when
    # we have raw text but no parsed sections yet — otherwise the candidate
    # page falls back to a naive split-by-heading render of the raw (often
    # column-scrambled) PDF text. Small countdown so the task reads the row
    # after the ingest transaction commits.
    try:
        cv_text = (getattr(app, "cv_text", "") or "").strip()
        if cv_text and getattr(app, "cv_sections", None) is None:
            from ..platform.config import settings

            if settings.CV_PARSE_BATCH_ENABLED:
                # The Message Batches sweep (submit_cv_parse_batches beat
                # task) picks up parse-pending rows every 15 min at 50% of
                # live pricing — no per-application enqueue needed.
                pass
            else:
                from ..tasks.automation_tasks import parse_application_cv_sections

                parse_application_cv_sections.apply_async(
                    (application_id,), countdown=15
                )
    except Exception:  # pragma: no cover — defensive
        logger.exception(
            "on_application_created cv-parse scheduling failed application_id=%s",
            application_id,
        )

    if score:
        try:
            # Reuse the orchestrator's enqueue path so caching, job-row
            # bookkeeping, and queue routing stay consistent with the
            # explicit Score / Rescore endpoints.
            from sqlalchemy.orm import Session

            from ..platform.database import SessionLocal
            from ..services.cv_score_orchestrator import enqueue_score

            db: Session = SessionLocal()
            try:
                from ..models.candidate_application import CandidateApplication

                live = (
                    db.query(CandidateApplication)
                    .filter(CandidateApplication.id == application_id)
                    .first()
                )
                if live is not None:
                    enqueue_score(db, live, force=score_force)
                    db.commit()
            finally:
                db.close()
        except Exception:  # pragma: no cover — defensive
            logger.exception(
                "on_application_created scoring enqueue failed application_id=%s",
                application_id,
            )

    # The score-completion task wakes the role immediately, so no separate
    # application-created wake is needed on the healthy path. The hourly
    # cohort sweep remains the recovery backstop if the initial score dispatch
    # is rejected during a transient broker outage.

    logger.info(
        "on_application_created enqueued application_id=%s score=%s",
        application_id,
        score,
    )
