import aiGenaiProductionReadinessTask from './productWalkthroughTask';

import { buildStandingCandidateReportModel } from '../candidates/assessmentViewModels';

const pickRepoFiles = (task, preferredPaths = []) => {
  const files = task?.repo_structure?.files && typeof task.repo_structure.files === 'object'
    ? task.repo_structure.files
    : {};
  const orderedPaths = [
    ...preferredPaths.filter((path) => path in files),
    ...Object.keys(files).filter((path) => !preferredPaths.includes(path)),
  ];

  return orderedPaths.map((path) => ({
    path,
    content: String(files[path] || ''),
  }));
};

const summarizeScenario = (scenario, maxParagraphs = 4) => (
  String(scenario || '')
    .split('\n\n')
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .slice(0, maxParagraphs)
    .join('\n\n')
);

const AI_RUNTIME_REPO_FILES = pickRepoFiles(aiGenaiProductionReadinessTask, [
  'README.md',
  'RISKS.md',
  'docs/launch_checklist.md',
  'intelligence/config.py',
  'intelligence/review.py',
  'intelligence/analyzer.py',
  'tests/test_analyzer.py',
]);

const AI_RUNTIME_OUTPUT = [
  '$ pytest -q --tb=short',
  'FAILED tests/test_analyzer.py::test_handles_llm_failure_gracefully',
  'FAILED tests/test_review.py::test_medium_confidence_high_risk_action_requires_review',
  'FAILED tests/test_retrieval.py::test_retriever_returns_grounded_context_documents',
].join('\n');

export const AI_SHOWCASE_APPLICATION = {
  id: 9001,
  candidate_name: 'Candidate walkthrough',
  candidate_email: '',
  candidate_position: 'AI Engineer',
  role_name: 'AI Engineer',
  pipeline_stage: 'technical review',
  application_outcome: 'review',
  workable_sourced: true,
  workable_score_raw: 74,
  created_at: '2026-04-21T09:42:00.000Z',
  updated_at: '2026-04-21T11:08:00.000Z',
  score_summary: {
    assessment_status: 'completed',
  },
  screening_interview_summary: {
    fireflies: {
      status: 'linked',
      configured: true,
      capture_expected: true,
      invite_email: 'taali@fireflies.ai',
      latest_summary:
        'Transcript attached. Recruiters can revisit how the candidate framed risk, where they used AI, and what they escalated instead of auto-shipping.',
      latest_source: 'Fireflies transcript',
      latest_meeting_date: '2026-04-21T10:00:00.000Z',
    },
  },
};

export const AI_SHOWCASE_COMPLETED_ASSESSMENT = {
  id: 1042,
  status: 'completed',
  role_name: 'AI Engineer',
  taali_score: 81,
  assessment_score: 84,
  final_score: 84,
  role_fit_score: 78,
  cv_job_match_score: 76,
  total_duration_seconds: 36 * 60,
  tests_passed: 7,
  tests_total: 8,
  completed_at: '2026-04-21T10:36:00.000Z',
  total_prompts: 9,
  prompt_quality_score: 8.4,
  browser_focus_ratio: 0.93,
  tab_switch_count: 4,
  calibration_score: 8.1,
  prompt_fraud_flags: [],
  score_breakdown: {
    heuristic_summary:
      'The candidate uses AI as a reviewer, not an autopilot. The strongest signal is how they catch unsafe defaults and keep release judgment anchored in risk, evidence, and escalation paths.',
    category_scores: {
      task_completion: 8.4,
      prompt_clarity: 8.6,
      context_provision: 8.4,
      independence_efficiency: 8.0,
      response_utilization: 8.3,
      debugging_design: 8.5,
      written_communication: 7.8,
    },
    score_components: {
      taali_score: 81,
      assessment_score: 84,
      role_fit_score: 78,
      cv_fit_score: 76,
      requirements_fit_score: 80,
    },
  },
  cv_job_match_details: {
    score_scale: '0-100',
    role_fit_score_100: 78,
    summary:
      'Strong fit for an AI engineer role where release safety, prompt judgment, and production readiness matter as much as shipping speed.',
    score_rationale_bullets: [
      'Reads the system risk first and scopes AI use carefully.',
      'Spots unsafe defaults and checks whether AI suggestions should be trusted.',
      'Keeps launch decisions tied to compliance and reliability, not just passing tests.',
    ],
    requirements_match_score_100: 80,
    requirements_coverage: {
      total: 4,
      met: 3,
      partially_met: 1,
      missing: 0,
    },
    requirements_assessment: [
      {
        requirement: 'Communicate residual launch risk clearly',
        priority: 'must_have',
        status: 'partially_met',
        evidence: 'Good judgment overall, but the handoff language still needs to be sharper for legal and compliance stakeholders.',
        impact: 'Probe how they would explain the smallest safe release to non-engineering decision-makers.',
      },
    ],
    matching_skills: [
      'AI-assisted debugging',
      'Prompt design under constraints',
      'Release judgment',
      'Production risk triage',
    ],
    missing_skills: ['Deeper compliance stakeholder framing'],
    experience_highlights: [
      'Used AI to accelerate repo reading without outsourcing the critical decisions.',
    ],
    concerns: [
      'Follow up on how they would communicate what still blocks launch after the patch set.',
    ],
  },
};

export const PRODUCT_WALKTHROUGH = {
  runtime: {
    taskName: aiGenaiProductionReadinessTask.name,
    taskRole: 'AI Engineer',
    taskContext: summarizeScenario(aiGenaiProductionReadinessTask.scenario),
    repoFiles: AI_RUNTIME_REPO_FILES,
    initialSelectedRepoPath: 'intelligence/analyzer.py',
    initialClaudePrompt:
      'Prioritize the highest-risk launch blockers first, then outline the smallest safe patch sequence for this regulated GenAI release.',
    claudeConversation: [
      {
        role: 'user',
        content:
          'Prioritize the highest-risk launch blockers first, then outline the smallest safe patch sequence for this regulated GenAI release.',
      },
    ],
    output: AI_RUNTIME_OUTPUT,
  },
  report: {
    reportModel: buildStandingCandidateReportModel({
      application: AI_SHOWCASE_APPLICATION,
      completedAssessment: AI_SHOWCASE_COMPLETED_ASSESSMENT,
      identity: {
        assessmentId: AI_SHOWCASE_COMPLETED_ASSESSMENT.id,
        sectionLabel: 'Standing report',
        name: AI_SHOWCASE_APPLICATION.candidate_name,
        email: AI_SHOWCASE_APPLICATION.candidate_email,
        position: AI_SHOWCASE_APPLICATION.candidate_position,
        taskName: aiGenaiProductionReadinessTask.name,
        roleName: AI_SHOWCASE_APPLICATION.role_name,
        applicationStatus: AI_SHOWCASE_APPLICATION.application_outcome,
        durationLabel: '36 min',
        completedLabel: 'Apr 21, 2026',
      },
    }),
    hero: {
      eyebrow: 'Candidate standing report',
      title: 'Candidate walkthrough',
      subtitle:
        'The recruiter side keeps the AI-collaboration read, Workable context, and transcript-backed interview evidence in one place.',
      stageLabel: `Stage · ${AI_SHOWCASE_APPLICATION.pipeline_stage}`,
      outcomeLabel: `Outcome · ${AI_SHOWCASE_APPLICATION.application_outcome}`,
      workableLabel: 'Synced from Workable',
      stats: [
        {
          key: 'taali',
          label: 'Taali score',
          value: '81',
          description: 'AI-collaboration and delivery signal',
          highlight: true,
        },
        {
          key: 'role-fit',
          label: 'Role fit',
          value: '78',
          description: 'Role and background alignment',
        },
        {
          key: 'assessment',
          label: 'Assessment',
          value: '84',
          description: 'Completed technical assessment',
        },
        {
          key: 'workable',
          label: 'Workable raw',
          value: '74',
          description: 'Existing ATS signal',
        },
      ],
    },
    workable: {
      workableRawScore: AI_SHOWCASE_APPLICATION.workable_score_raw,
      taaliScore: AI_SHOWCASE_COMPLETED_ASSESSMENT.taali_score,
      posted: false,
      workableProfileUrl: '',
      scorePrecedence: 'workable_first',
    },
  },
};

export const PRODUCT_WALKTHROUGH_TASK = {
  id: aiGenaiProductionReadinessTask.task_id,
  title: aiGenaiProductionReadinessTask.name,
  role: 'AI Engineer',
  durationLabel: `${aiGenaiProductionReadinessTask.duration_minutes} min`,
  stack: 'Python · Claude · Release safety',
  tools: 'Repo · Editor · Terminal · Claude',
  description:
    'Review a regulated GenAI launch, tighten the safety guardrails, and show how the candidate works with AI when the repo and launch pressure are both real.',
};

export const PRODUCT_WALKTHROUGH_START_DATA = {
  assessment_id: 9001,
  token: 'demo-product-walkthrough',
  candidate_name: 'Candidate walkthrough',
  organization_name: 'Taali demo',
  time_remaining: aiGenaiProductionReadinessTask.duration_minutes * 60,
  terminal_mode: false,
  task: {
    ...aiGenaiProductionReadinessTask,
    name: aiGenaiProductionReadinessTask.name,
    duration_minutes: aiGenaiProductionReadinessTask.duration_minutes,
    proctoring_enabled: false,
    claude_budget_limit_usd: 8,
  },
};

// Seed data for the showcase Jobs board (`/jobs?demo=1&showcase=1`).
// Shape mirrors the recruiter `roles.list({ include_pipeline_stats: true })` payload:
// fields used by JobsPage are id, name, source, workable_job_id, job_spec_present,
// applications_count, active_candidates_count, stage_counts, tasks_count,
// description, last_candidate_activity_at.
export const JOBS_SHOWCASE = [
  {
    id: 7001,
    name: 'AI Engineer',
    description: 'Production-ready GenAI engineer who can ship under release pressure.',
    source: 'workable',
    workable_job_id: 'wkbl-71224',
    job_spec_present: true,
    job_spec_filename: 'ai-engineer-spec.md',
    applications_count: 38,
    active_candidates_count: 24,
    tasks_count: 2,
    stage_counts: { applied: 12, invited: 6, in_assessment: 4, review: 2 },
    last_candidate_activity_at: '2026-04-26T16:42:00.000Z',
    auto_reject_threshold_100: 55,
  },
  {
    id: 7002,
    name: 'Senior Data Engineer',
    description: 'Owns the recovery playbooks for our nightly Glue pipelines.',
    source: 'workable',
    workable_job_id: 'wkbl-71338',
    job_spec_present: true,
    applications_count: 19,
    active_candidates_count: 11,
    tasks_count: 1,
    stage_counts: { applied: 4, invited: 3, in_assessment: 2, review: 2 },
    last_candidate_activity_at: '2026-04-25T09:18:00.000Z',
    auto_reject_threshold_100: 60,
  },
  {
    id: 7003,
    name: 'Frontend Engineer',
    description: 'Recruiter workspace UI and reporting surfaces.',
    source: 'manual',
    workable_job_id: null,
    job_spec_present: true,
    applications_count: 12,
    active_candidates_count: 7,
    tasks_count: 1,
    stage_counts: { applied: 5, invited: 1, in_assessment: 1, review: 0 },
    last_candidate_activity_at: '2026-04-24T14:55:00.000Z',
    auto_reject_threshold_100: null,
  },
  {
    id: 7004,
    name: 'Staff Backend Engineer',
    description: 'Draft role — scoring policy not configured yet.',
    source: 'manual',
    workable_job_id: null,
    job_spec_present: false,
    applications_count: 0,
    active_candidates_count: 0,
    tasks_count: 0,
    stage_counts: { applied: 0, invited: 0, in_assessment: 0, review: 0 },
    last_candidate_activity_at: null,
    auto_reject_threshold_100: null,
  },
];

// Org payload returned alongside the roles list. Drives the Workable strip on
// JobsPage (sync status, last pull, summary counts).
export const JOBS_SHOWCASE_ORG = {
  workable_connected: true,
  workable_last_sync_at: '2026-04-27T08:12:00.000Z',
  workable_last_sync_status: 'success',
  workable_last_sync_summary: {
    new_candidates: 4,
    candidates_seen: 35,
  },
  workable_config: { sync_interval_minutes: 60 },
  workable_sync_progress: null,
  workable_sync_started_at: null,
};

// Seed data for the showcase Candidates directory (`/candidates?demo=1&showcase=1`).
// Shape mirrors `roles.listApplicationsGlobal()`: id, candidate_name, candidate_email,
// role_id, role_name, pipeline_stage, application_outcome, pre_screen_score,
// taali_score, score_summary, score_status, source, workable_*, created_at,
// pipeline_stage_updated_at.
export const CANDIDATES_DIRECTORY_SHOWCASE = [
  {
    id: 88101,
    candidate_id: 22101,
    candidate_name: 'Priya Raman',
    candidate_email: 'priya.raman@example.com',
    role_id: 7001,
    role_name: 'AI Engineer',
    pipeline_stage: 'review',
    application_outcome: 'open',
    pre_screen_score: 86,
    taali_score: 81,
    score_summary: { taali_score: 81, assessment_status: 'completed', assessment_id: 1042 },
    score_status: 'done',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-91',
    workable_stage: 'Technical review',
    workable_score_raw: 74,
    created_at: '2026-04-19T10:11:00.000Z',
    pipeline_stage_updated_at: '2026-04-21T11:08:00.000Z',
    valid_assessment_id: 1042,
    schema_version: 1,
  },
  {
    id: 88102,
    candidate_id: 22102,
    candidate_name: 'Diego Alvarez',
    candidate_email: 'diego.alvarez@example.com',
    role_id: 7001,
    role_name: 'AI Engineer',
    pipeline_stage: 'in_assessment',
    application_outcome: 'open',
    pre_screen_score: 78,
    taali_score: null,
    score_summary: { assessment_status: 'in_progress' },
    score_status: 'done',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-92',
    workable_stage: 'Assessment sent',
    workable_score_raw: 69,
    created_at: '2026-04-21T08:31:00.000Z',
    pipeline_stage_updated_at: '2026-04-26T09:50:00.000Z',
    schema_version: 1,
  },
  {
    id: 88103,
    candidate_id: 22103,
    candidate_name: 'Hannah Okonkwo',
    candidate_email: 'hannah.okonkwo@example.com',
    role_id: 7001,
    role_name: 'AI Engineer',
    pipeline_stage: 'invited',
    application_outcome: 'open',
    pre_screen_score: 72,
    taali_score: null,
    score_summary: { assessment_status: 'invited' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-22T14:02:00.000Z',
    pipeline_stage_updated_at: '2026-04-23T10:14:00.000Z',
    schema_version: 1,
  },
  {
    id: 88104,
    candidate_id: 22104,
    candidate_name: 'Marcus Lin',
    candidate_email: 'marcus.lin@example.com',
    role_id: 7001,
    role_name: 'AI Engineer',
    pipeline_stage: 'applied',
    application_outcome: 'open',
    pre_screen_score: 64,
    taali_score: null,
    score_summary: { assessment_status: 'pending_cv' },
    score_status: 'pending',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-94',
    workable_stage: 'Sourced',
    created_at: '2026-04-26T18:20:00.000Z',
    pipeline_stage_updated_at: '2026-04-26T18:20:00.000Z',
    schema_version: 1,
  },
  {
    id: 88105,
    candidate_id: 22105,
    candidate_name: 'Sofia Russo',
    candidate_email: 'sofia.russo@example.com',
    role_id: 7001,
    role_name: 'AI Engineer',
    pipeline_stage: 'applied',
    application_outcome: 'open',
    pre_screen_score: 59,
    taali_score: null,
    score_summary: { assessment_status: 'pending_cv' },
    score_status: 'pending',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-95',
    workable_stage: 'Sourced',
    created_at: '2026-04-26T18:32:00.000Z',
    pipeline_stage_updated_at: '2026-04-26T18:32:00.000Z',
    schema_version: 1,
  },
  {
    id: 88106,
    candidate_id: 22106,
    candidate_name: 'Theo Becker',
    candidate_email: 'theo.becker@example.com',
    role_id: 7002,
    role_name: 'Senior Data Engineer',
    pipeline_stage: 'review',
    application_outcome: 'open',
    pre_screen_score: 88,
    taali_score: 79,
    score_summary: { taali_score: 79, assessment_status: 'completed', assessment_id: 1101 },
    score_status: 'done',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-96',
    workable_stage: 'Technical review',
    workable_score_raw: 71,
    created_at: '2026-04-15T11:00:00.000Z',
    pipeline_stage_updated_at: '2026-04-22T13:18:00.000Z',
    valid_assessment_id: 1101,
    schema_version: 1,
  },
  {
    id: 88107,
    candidate_id: 22107,
    candidate_name: 'Aisha Bello',
    candidate_email: 'aisha.bello@example.com',
    role_id: 7002,
    role_name: 'Senior Data Engineer',
    pipeline_stage: 'in_assessment',
    application_outcome: 'open',
    pre_screen_score: 74,
    taali_score: null,
    score_summary: { assessment_status: 'in_progress' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-20T08:55:00.000Z',
    pipeline_stage_updated_at: '2026-04-25T16:30:00.000Z',
    schema_version: 1,
  },
  {
    id: 88108,
    candidate_id: 22108,
    candidate_name: 'Kenji Watanabe',
    candidate_email: 'kenji.watanabe@example.com',
    role_id: 7002,
    role_name: 'Senior Data Engineer',
    pipeline_stage: 'invited',
    application_outcome: 'open',
    pre_screen_score: 68,
    taali_score: null,
    score_summary: { assessment_status: 'invited' },
    score_status: 'done',
    source: 'workable',
    workable_candidate_id: 'wkbl-cand-98',
    workable_stage: 'Assessment sent',
    workable_score_raw: 66,
    created_at: '2026-04-23T09:42:00.000Z',
    pipeline_stage_updated_at: '2026-04-24T17:11:00.000Z',
    schema_version: 1,
  },
  {
    id: 88109,
    candidate_id: 22109,
    candidate_name: 'Elena Marković',
    candidate_email: 'elena.markovic@example.com',
    role_id: 7002,
    role_name: 'Senior Data Engineer',
    pipeline_stage: 'applied',
    application_outcome: 'open',
    pre_screen_score: 62,
    taali_score: null,
    score_summary: { assessment_status: 'applied' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-25T12:18:00.000Z',
    pipeline_stage_updated_at: '2026-04-25T12:18:00.000Z',
    schema_version: 1,
  },
  {
    id: 88110,
    candidate_id: 22110,
    candidate_name: 'Ravi Shah',
    candidate_email: 'ravi.shah@example.com',
    role_id: 7003,
    role_name: 'Frontend Engineer',
    pipeline_stage: 'in_assessment',
    application_outcome: 'open',
    pre_screen_score: 81,
    taali_score: null,
    score_summary: { assessment_status: 'in_progress' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-22T10:08:00.000Z',
    pipeline_stage_updated_at: '2026-04-26T14:00:00.000Z',
    schema_version: 1,
  },
  {
    id: 88111,
    candidate_id: 22111,
    candidate_name: 'Lila Fischer',
    candidate_email: 'lila.fischer@example.com',
    role_id: 7003,
    role_name: 'Frontend Engineer',
    pipeline_stage: 'applied',
    application_outcome: 'open',
    pre_screen_score: 70,
    taali_score: null,
    score_summary: { assessment_status: 'applied' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-24T15:44:00.000Z',
    pipeline_stage_updated_at: '2026-04-24T15:44:00.000Z',
    schema_version: 1,
  },
  {
    id: 88112,
    candidate_id: 22112,
    candidate_name: 'Tomás Pereira',
    candidate_email: 'tomas.pereira@example.com',
    role_id: 7003,
    role_name: 'Frontend Engineer',
    pipeline_stage: 'applied',
    application_outcome: 'open',
    pre_screen_score: 67,
    taali_score: null,
    score_summary: { assessment_status: 'applied' },
    score_status: 'done',
    source: 'manual',
    created_at: '2026-04-26T09:16:00.000Z',
    pipeline_stage_updated_at: '2026-04-26T09:16:00.000Z',
    schema_version: 1,
  },
];

// Aggregate stage counts derived from CANDIDATES_DIRECTORY_SHOWCASE — used by
// the directory's stage-filter chips. Kept in sync manually with the seed list above.
export const CANDIDATES_DIRECTORY_STAGE_COUNTS = {
  all: 12,
  applied: 6,
  invited: 2,
  in_assessment: 3,
  review: 2,
};
