#!/usr/bin/env bash
# Regenerate Taali's vendored @mainspring/ui ErrorBoundary source from the
# canonical source in the mainspring checkout.
#
# Why: Taali is the live brand on its own Vite/React stack, but it consumes the
# shared ErrorBoundary machinery from mainspring. The CSS-var palette arrives
# separately via 00-tokens.css (vendor_mainspring_tokens.sh). Only the source
# that Taali imports is copied; the generated directory is never hand-edited.
# The WS-E release bot re-runs this script to adopt a new mainspring tag.
#
# Re-run + commit whenever mainspring's FE primitives change:
#     bash scripts/vendor_mainspring_ui.sh && git add -A frontend/vendor && git commit
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAINSPRING_SRC="${MAINSPRING_SRC:-$(cd "$HERE/../mainspring" && pwd)}"
DEST="$HERE/frontend/vendor/mainspring"

UI_SRC="$MAINSPRING_SRC/frontend/packages/ui/src"
ERROR_BOUNDARY_SRC="$UI_SRC/ErrorBoundary.tsx"

if [[ ! -f "$ERROR_BOUNDARY_SRC" ]]; then
  echo "missing Mainspring ErrorBoundary source: $ERROR_BOUNDARY_SRC" >&2
  exit 1
fi

echo "vendoring @mainspring/ui ErrorBoundary: $ERROR_BOUNDARY_SRC -> $DEST/ui"

rm -rf "$DEST/ui" "$DEST/tokens"
mkdir -p "$DEST/ui"
rsync -a "$ERROR_BOUNDARY_SRC" "$DEST/ui/ErrorBoundary.tsx"

# Record the source ref so the bot's adopt-PR is auditable.
REF="$(git -C "$MAINSPRING_SRC" rev-parse HEAD 2>/dev/null || echo unknown)"
{
  echo "# Source ref for frontend/vendor/mainspring (generated by scripts/vendor_mainspring_ui.sh)"
  echo "mainspring=$REF"
  echo "vendored_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$DEST/MAINSPRING_REF.txt"

echo "vendored ui/ErrorBoundary.tsx; ref $REF"
