#!/usr/bin/env bash
# Regenerate Taali's vendored @mainspring/tokens stylesheet
# (frontend/src/styles/00-tokens.css) from the canonical source in the
# mainspring checkout.
#
# Why: Taali is the live brand on its own Vite/React stack, but it consumes
# the SHARED design-token vocabulary (the brand-invariant structure + the
# per-brand [data-brand] palettes) from mainspring so the brands never drift.
# The brand-invariant + [data-brand] blocks in 00-tokens.css are therefore
# generated, never hand-edited; Taali-specific (hiring) tokens live in
# 01-base.css. This script is the one source of truth for the generated file
# so the WS-E release bot can re-vendor it deterministically.
#
# The canonical Google-Fonts @import is intentionally dropped: index.html owns
# font loading (preload + print-swap) for Taali.
#
# Re-run + commit whenever mainspring's tokens change:
#     bash scripts/vendor_mainspring_tokens.sh && git add -A frontend/src/styles && git commit
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAINSPRING_SRC="${MAINSPRING_SRC:-$(cd "$HERE/../mainspring" && pwd)}"
SRC="$MAINSPRING_SRC/frontend/packages/tokens/src/tokens.css"
DEST="$HERE/frontend/src/styles/00-tokens.css"

echo "vendoring @mainspring/tokens: $SRC -> $DEST"

{
  cat <<'HEADER'
/* ============================================================
   00-tokens.css — VENDORED from @mainspring/tokens (hex model).

   GENERATED by scripts/vendor_mainspring_tokens.sh — do NOT hand-edit.
   Source of truth: mainspring/frontend/packages/tokens/src/tokens.css.
   Taali-specific (hiring) tokens live in 01-base.css, not here.

   Taali selects its palette via `data-brand="taali"` on <html>
   (set statically in index.html so the first paint is purple, never
   the mainspring mint fallback). Dark mode is opt-in via
   `html[data-theme="dark"]`.

   The Google-Fonts @import is intentionally omitted: index.html owns
   font loading (preload + print-swap) for Taali.

   NOTE on Tailwind: colours map to plain `var(--x)`, so the
   `<alpha-value>` opacity modifier (e.g. `bg-bg/95`) is NOT available
   — use `color-mix(...)` for translucency.
   ============================================================ */
HEADER
  # Emit the canonical body, starting at the first structural block
  # (drops the upstream header comment and the Google-Fonts @import).
  awk '/Brand-invariant structure/{p=1} p' "$SRC"
} > "$DEST"

echo "wrote $(wc -l < "$DEST" | tr -d ' ') lines -> $DEST"
